name: Scrape Detail Chapter (Kura-kura)
on:
  schedule:
    # Menjalankan setiap hari jam 00:00 UTC (dini hari)
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: node scraper_lama.js # Ini menjalankan skrip pengambil chapter
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Chore(Kura-kura): Arsip data chapter komik'
          file_pattern: 'data/comics/ data/kura_kura_chapter_status.json'
