# Nama workflow untuk robot Badak
name: Bangun Arsip Komik (Badak)

# Pemicu workflow
on:
  # HANYA BISA DIJALANKAN MANUAL
  # Tidak ada jadwal 'schedule'
  workflow_dispatch:

# Izin untuk menulis ke repo
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Jalankan Robot Badak
        run: node scraper_badak.js

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Build(Badak): Mempercepat pembangunan arsip komik'
          # Menyimpan file arsip utama dan file status si Badak
          file_pattern: 'data/archive-list.json data/badak_status.json'
