name: Scrape Latest Comics

on:
  schedule:
    # Menjalankan setiap 1 jam sekali
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm start

      # *** INI DIA PERBAIKANNYA ***
      # Menggunakan versi terbaru dari 'Tukang Arsip'
      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            debug/screenshot.png
            debug/page.html
            debug/hasil_data.json
            
